# Utilizando o Plugin do VSCode - Rest Client
# Estou utilizando este para que também sirva de documentação

@baseUrl = http://localhost:3000
@jsonPlaceholder = https://jsonplaceholder.typicode.com

###

GET {{baseUrl}}

### 

# GET All Clients
GET {{baseUrl}}/api/clients

### 

# GET Clients by ID
GET {{baseUrl}}/api/clients/2

###

# POST Create Client

POST {{baseUrl}}/api/clients 
Content-Type: application/json

{
  "name": "Nicolas Breno Nelson Silva",
  "cpf": "929.822.835-06",
  "phone": "(27) 2734-9247",
  "email": "nicolasbrenonelsonsilva-95@tita.com.br",
  "address": "Rua Vinte e Cinco, 657"
}

###

PUT {{baseUrl}}/api/clients/4
Content-Type: application/json

{
  "name": "Alexandre Iago da Conceição",
  "cpf": "291.641.207-75",
  "phone": "(81) 2678-7782",
  "email": "alexandreiagodaconceicao_@arganet.com.br",
  "address": "Rua Líbano, 650"
}

### 

# GET Clients by ID
DELETE {{baseUrl}}/api/clients/3

### 

# suppliers
GET {{baseUrl}}/api/supplies

### 

# products
GET {{baseUrl}}/api/products

### 

# sales
GET {{baseUrl}}/api/sales

###

GET {{jsonPlaceholder}}/todos/1 

###

POST {{jsonPlaceholder}}/todos 
Content-Type: application/json

{
  "nome": "teste"
}
