# Utilizando o Plugin do VSCode - Rest Client
# Estou utilizando este para que também sirva de documentação

@baseUrl = http://localhost:3000
@jsonPlaceholder = https://jsonplaceholder.typicode.com

###

GET {{baseUrl}}

### 

# get Clients
GET {{baseUrl}}/api/clients

###

# Salvar Cliente

POST {{baseUrl}}/api/clients 
Content-Type: application/json

{
  "name": "Nicolas Breno Nelson Silva",
  "cpf": "929.822.835-06",
  "phone": "(27) 2734-9247",
  "email": "nicolasbrenonelsonsilva-95@tita.com.br",
  "address": "Rua Vinte e Cinco, 657"
}

### 

# suppliers
GET {{baseUrl}}/api/supplies

### 

# products
GET {{baseUrl}}/api/products

### 

# sales
GET {{baseUrl}}/api/sales

###

GET {{jsonPlaceholder}}/todos/1 

###

POST {{jsonPlaceholder}}/todos 
Content-Type: application/json

{
  "nome": "teste"
}
